// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaSmartWeb.Models;

#nullable disable

namespace PharmaSmartWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412213029_AddPricingScreen")]
    partial class AddPricingScreen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("MappingId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountMappings");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.ToTable("AccountingTemplates");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplateLine", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LineId"));

                    b.Property<bool>("IsDebit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.HasIndex("TemplateId");

                    b.ToTable("AccountingTemplateLines");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("AccountID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("AccountNature")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("AccountNature");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchId");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("CreatedBy");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsParent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsParent");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ParentAccountID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("AccountId")
                        .HasName("PRIMARY");

                    b.HasIndex("AccountCode")
                        .IsUnique()
                        .HasDatabaseName("AccountCode");

                    b.HasIndex("BranchId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BarcodeGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BatchNumber");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("CurrentPrice");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugId");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("ExpiryDate");

                    b.Property<string>("GeneratedCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("GeneratedCode");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsPrinted");

                    b.Property<int>("QuantityToPrint")
                        .HasColumnType("int(11)")
                        .HasColumnName("QuantityToPrint");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.HasIndex("UserId");

                    b.ToTable("barcodegenerator");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BranchAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BranchId");

                    b.ToTable("branch_accounts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branches", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("DefaultCOGSAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultCashAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultCurrencyId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultInventoryAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultSalesAccountId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasColumnType("varchar(200)");

                    b.HasKey("BranchId")
                        .HasName("PRIMARY");

                    b.HasIndex("BranchCode")
                        .IsUnique()
                        .HasDatabaseName("BranchCode");

                    b.HasIndex("DefaultCOGSAccountId");

                    b.HasIndex("DefaultCashAccountId");

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("DefaultInventoryAccountId");

                    b.HasIndex("DefaultSalesAccountId");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branchinventory", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<string>("Abccategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasColumnName("ABCCategory")
                        .HasDefaultValueSql("'C'");

                    b.Property<decimal?>("AverageCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentSellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("int(11)");

                    b.HasKey("BranchId", "DrugId")
                        .HasName("PRIMARY");

                    b.HasIndex("DrugId");

                    b.ToTable("branchinventory");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CompanyLogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Currencies", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("CurrencyId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBaseCurrency")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CurrencyId");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("CustomerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex("AccountId");

                    b.HasIndex("BranchId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.DrugBatches", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("BatchId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugId");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("date");

                    b.HasKey("BatchId");

                    b.HasIndex("DrugId");

                    b.ToTable("drug_batches");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugs", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("Barcode")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ConversionFactor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int(11)")
                        .HasColumnName("GroupId");

                    b.Property<string>("ImagePath")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsLifeSaving")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MainUnit")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SaremaCategory")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SubUnit")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("DrugId");

                    b.HasIndex("GroupId");

                    b.ToTable("drugs");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransferdetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("DetailID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("TransferId")
                        .HasColumnType("int(11)")
                        .HasColumnName("TransferID");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("TransferId");

                    b.ToTable("drugtransferdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransfers", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("TransferID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<int>("FromBranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("FromBranchID");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("ReceiptJournalId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ToBranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ToBranchID");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransferId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ToBranchId");

                    b.ToTable("drugtransfers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Employees", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("EmployeeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Forecasts", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ForecastID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("date");

                    b.Property<int>("PredictedDemand")
                        .HasColumnType("int(11)");

                    b.HasKey("ForecastId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.ToTable("forecasts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Fundtransfers", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("TransferID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("CreatedBy");

                    b.Property<int>("FromAccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("FromAccountID");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int(11)")
                        .HasColumnName("JournalId");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToAccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ToAccountID");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransferId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("JournalId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("fundtransfers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.ItemGroups", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("GroupId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GroupCode");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GroupName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.HasKey("GroupId");

                    b.ToTable("itemgroups");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journaldetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("DetailID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("AccountID");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("JournalId")
                        .HasColumnType("int(11)")
                        .HasColumnName("JournalID");

                    b.HasKey("DetailId");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalId");

                    b.ToTable("journaldetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journalentries", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("JournalID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JournalId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("varchar(50)");

                    b.HasKey("JournalId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("journalentries");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PlanId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("CreatedBy");

                    b.Property<decimal>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PlanId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("purchaseplans");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlanDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("DetailId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ABCCategory")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugId");

                    b.Property<decimal>("ForecastAccuracy")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ForecastedDemand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsLifeSaving")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PlanId");

                    b.Property<int>("ProposedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCostEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PlanId");

                    b.ToTable("purchaseplandetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchasedetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("DetailID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BonusQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("PurchaseID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchasedetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchases", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PurchaseID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InvoiceImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserID");

                    b.HasKey("PurchaseId");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SalePayments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PaymentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("SaleId");

                    b.HasKey("PaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_payments");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Saledetails", b =>
                {
                    b.Property<int>("SaleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("SaleDetailID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SaleDetailId"));

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("SaleID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("SaleDetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SaleId");

                    b.ToTable("saledetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Sales", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("SaleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int(11)")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReturn")
                        .IsConcurrencyToken()
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ParentSaleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserID");

                    b.HasKey("SaleId")
                        .HasName("PRIMARY");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Screenpermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("PermissionID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("CanAdd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanPrint")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("RoleID");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ScreenID");

                    b.HasKey("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("screenpermissions");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Seasonaldata", b =>
                {
                    b.Property<int>("SeasonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("SeasonalID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeasonalId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SeasonalFactor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("int(11)");

                    b.HasKey("SeasonalId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.ToTable("seasonaldata");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Shelves", b =>
                {
                    b.Property<int>("ShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ShelfId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShelfId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int(11)")
                        .HasColumnName("GroupId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Notes");

                    b.Property<string>("ShelfName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ShelfName");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("WarehouseId");

                    b.HasKey("ShelfId");

                    b.HasIndex("GroupId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("shelves");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockauditdetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<int>("Difference")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)");

                    b.Property<int>("PhysicalQty")
                        .HasColumnType("int");

                    b.Property<int>("SystemQty")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("AuditId");

                    b.HasIndex("DrugId");

                    b.ToTable("stockauditdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockaudits", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("AuditId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("stockaudits");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockmovements", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("MovementID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DrugID");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ReferenceID");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("UserID");

                    b.HasKey("MovementId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.HasIndex("UserId");

                    b.ToTable("stockmovements");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Suppliers", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("SupplierId");

                    b.HasIndex("AccountId");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SystemLogs", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("ScreenName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("systemlogs");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Systemscreens", b =>
                {
                    b.Property<int>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ScreenID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScreenId"));

                    b.Property<string>("ScreenArabicName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ScreenCategory")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScreenId");

                    b.ToTable("systemscreens");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Userroles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("RoleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleArabicName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("userroles");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("UserID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("DefaultBranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DefaultBranchID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int(11)")
                        .HasColumnName("EmployeeID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("RoleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("DefaultBranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Vouchers", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<int>("FromAccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("FromAccountID");

                    b.Property<int>("ToAccountId")
                        .HasColumnType("int(11)")
                        .HasColumnName("ToAccountID");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("VoucherDate");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("VoucherType");

                    b.HasKey("VoucherId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Warehouses", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("WarehouseId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)")
                        .HasColumnName("BranchId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Location");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("WarehouseName");

                    b.HasKey("WarehouseId");

                    b.HasIndex("BranchId");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountMapping", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplateLine", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.AccountingTemplate", "Template")
                        .WithMany("Lines")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Accounts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ParentAccount")
                        .WithMany("SubAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BarcodeGenerator", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("BarcodeQueue")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("BarcodeGenerator")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BranchAccounts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("BranchAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("BranchAccounts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branches", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultCOGSAccount")
                        .WithMany("CogsBranches")
                        .HasForeignKey("DefaultCOGSAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultCashAccount")
                        .WithMany("CashBranches")
                        .HasForeignKey("DefaultCashAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Currencies", "DefaultCurrency")
                        .WithMany("Branches")
                        .HasForeignKey("DefaultCurrencyId");

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultInventoryAccount")
                        .WithMany("InventoryBranches")
                        .HasForeignKey("DefaultInventoryAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultSalesAccount")
                        .WithMany("SalesBranches")
                        .HasForeignKey("DefaultSalesAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultCOGSAccount");

                    b.Navigation("DefaultCashAccount");

                    b.Navigation("DefaultCurrency");

                    b.Navigation("DefaultInventoryAccount");

                    b.Navigation("DefaultSalesAccount");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branchinventory", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Branchinventory")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Branchinventory")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Customers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Customers")
                        .HasForeignKey("AccountId")
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.DrugBatches", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("DrugBatches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugs", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.ItemGroups", "ItemGroup")
                        .WithMany("Drugs")
                        .HasForeignKey("GroupId");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransferdetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Drugtransferdetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugtransfers", "Transfer")
                        .WithMany("Drugtransferdetails")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransfers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Users", "CreatedByNavigation")
                        .WithMany("Drugtransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "FromBranch")
                        .WithMany("DrugtransfersFromBranch")
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "ReceivedByNavigation")
                        .WithMany()
                        .HasForeignKey("ReceivedBy");

                    b.HasOne("PharmaSmartWeb.Models.Branches", "ToBranch")
                        .WithMany("DrugtransfersToBranch")
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("FromBranch");

                    b.Navigation("ReceivedByNavigation");

                    b.Navigation("ToBranch");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Employees", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Forecasts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Forecasts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Forecasts")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Fundtransfers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Fundtransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "FromAccount")
                        .WithMany("FundtransfersFromAccount")
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Journalentries", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ToAccount")
                        .WithMany("FundtransfersToAccount")
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("FromAccount");

                    b.Navigation("Journal");

                    b.Navigation("ToAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journaldetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Journaldetails")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Journalentries", "Journal")
                        .WithMany("Journaldetails")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journalentries", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Journalentries")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "CreatedByNavigation")
                        .WithMany("Journalentries")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlan", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlanDetail", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.PurchasePlan", "PurchasePlan")
                        .WithMany("PlanDetails")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("PurchasePlan");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchasedetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Purchasedetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Purchases", "Purchase")
                        .WithMany("Purchasedetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchases", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Purchases")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Suppliers", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SalePayments", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("SalePayments")
                        .HasForeignKey("AccountId");

                    b.HasOne("PharmaSmartWeb.Models.Sales", "Sale")
                        .WithMany("SalePayments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Saledetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Saledetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Sales", "Sale")
                        .WithMany("Saledetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Sales", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Sales")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Customers", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Screenpermissions", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Userroles", "Role")
                        .WithMany("Screenpermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Systemscreens", "Screen")
                        .WithMany("Screenpermissions")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Seasonaldata", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Seasonaldata")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Seasonaldata")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Shelves", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.ItemGroups", "ItemGroup")
                        .WithMany("Shelves")
                        .HasForeignKey("GroupId");

                    b.HasOne("PharmaSmartWeb.Models.Warehouses", "Warehouse")
                        .WithMany("Shelves")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemGroup");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockauditdetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Stockaudits", "Audit")
                        .WithMany("Stockauditdetails")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockaudits", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Stockaudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockmovements", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Stockmovements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Stockmovements")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Stockmovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Drug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Suppliers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Suppliers")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SystemLogs", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Systemlogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Users", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "DefaultBranch")
                        .WithMany("Users")
                        .HasForeignKey("DefaultBranchId");

                    b.HasOne("PharmaSmartWeb.Models.Employees", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PharmaSmartWeb.Models.Userroles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultBranch");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Vouchers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "FromAccount")
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("FromAccount");

                    b.Navigation("ToAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Warehouses", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Warehouses")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Accounts", b =>
                {
                    b.Navigation("BranchAccounts");

                    b.Navigation("CashBranches");

                    b.Navigation("CogsBranches");

                    b.Navigation("Customers");

                    b.Navigation("FundtransfersFromAccount");

                    b.Navigation("FundtransfersToAccount");

                    b.Navigation("InventoryBranches");

                    b.Navigation("Journaldetails");

                    b.Navigation("SalePayments");

                    b.Navigation("SalesBranches");

                    b.Navigation("SubAccounts");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branches", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BranchAccounts");

                    b.Navigation("Branchinventory");

                    b.Navigation("DrugtransfersFromBranch");

                    b.Navigation("DrugtransfersToBranch");

                    b.Navigation("Employees");

                    b.Navigation("Forecasts");

                    b.Navigation("Journalentries");

                    b.Navigation("Purchases");

                    b.Navigation("Sales");

                    b.Navigation("Seasonaldata");

                    b.Navigation("Stockmovements");

                    b.Navigation("Users");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Currencies", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Customers", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugs", b =>
                {
                    b.Navigation("BarcodeQueue");

                    b.Navigation("Branchinventory");

                    b.Navigation("DrugBatches");

                    b.Navigation("Drugtransferdetails");

                    b.Navigation("Forecasts");

                    b.Navigation("Purchasedetails");

                    b.Navigation("Saledetails");

                    b.Navigation("Seasonaldata");

                    b.Navigation("Stockmovements");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransfers", b =>
                {
                    b.Navigation("Drugtransferdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Employees", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.ItemGroups", b =>
                {
                    b.Navigation("Drugs");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journalentries", b =>
                {
                    b.Navigation("Journaldetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlan", b =>
                {
                    b.Navigation("PlanDetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchases", b =>
                {
                    b.Navigation("Purchasedetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Sales", b =>
                {
                    b.Navigation("SalePayments");

                    b.Navigation("Saledetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockaudits", b =>
                {
                    b.Navigation("Stockauditdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Systemscreens", b =>
                {
                    b.Navigation("Screenpermissions");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Userroles", b =>
                {
                    b.Navigation("Screenpermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Users", b =>
                {
                    b.Navigation("BarcodeGenerator");

                    b.Navigation("Drugtransfers");

                    b.Navigation("Fundtransfers");

                    b.Navigation("Journalentries");

                    b.Navigation("Purchases");

                    b.Navigation("Sales");

                    b.Navigation("Stockaudits");

                    b.Navigation("Stockmovements");

                    b.Navigation("Systemlogs");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Warehouses", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
