// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaSmartWeb.Models;

namespace PharmaSmartWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("MappingId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountMappings");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TemplateName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.ToTable("AccountingTemplates");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplateLine", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDebit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.HasIndex("TemplateId");

                    b.ToTable("AccountingTemplateLines");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountID")
                        .HasColumnType("int(11)");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("AccountNature")
                        .HasColumnName("AccountNature")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BranchId")
                        .HasColumnName("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsParent")
                        .HasColumnName("IsParent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnName("ParentAccountID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnName("UpdatedBy")
                        .HasColumnType("int(11)");

                    b.HasKey("AccountId")
                        .HasName("PRIMARY");

                    b.HasIndex("AccountCode")
                        .IsUnique()
                        .HasName("AccountCode");

                    b.HasIndex("BranchId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BarcodeGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnName("BatchNumber")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnName("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnName("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("GeneratedCode")
                        .IsRequired()
                        .HasColumnName("GeneratedCode")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsPrinted")
                        .HasColumnName("IsPrinted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuantityToPrint")
                        .HasColumnName("QuantityToPrint")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.HasIndex("UserId");

                    b.ToTable("barcodegenerator");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BranchAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BranchId");

                    b.ToTable("branch_accounts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branches", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("DefaultCOGSAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultCashAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultCurrencyId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultInventoryAccountId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultSalesAccountId")
                        .HasColumnType("int(11)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasColumnType("varchar(200)");

                    b.HasKey("BranchId")
                        .HasName("PRIMARY");

                    b.HasIndex("BranchCode")
                        .IsUnique()
                        .HasName("BranchCode");

                    b.HasIndex("DefaultCOGSAccountId");

                    b.HasIndex("DefaultCashAccountId");

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("DefaultInventoryAccountId");

                    b.HasIndex("DefaultSalesAccountId");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branchinventory", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Abccategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ABCCategory")
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("'C'");

                    b.Property<decimal?>("AverageCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CurrentSellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("int(11)");

                    b.HasKey("BranchId", "DrugId")
                        .HasName("PRIMARY");

                    b.HasIndex("DrugId");

                    b.ToTable("branchinventory");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("CompanyLogoPath")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("TaxNumber")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Currencies", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CurrencyId")
                        .HasColumnType("int(11)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBaseCurrency")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CurrencyId");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerID")
                        .HasColumnType("int(11)");

                    b.Property<int>("AccountId")
                        .HasColumnName("AccountID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex("AccountId");

                    b.HasIndex("BranchId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.DrugBatches", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BatchId")
                        .HasColumnType("int(11)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("date");

                    b.HasKey("BatchId");

                    b.HasIndex("DrugId");

                    b.ToTable("drug_batches");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugs", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Barcode")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ConversionFactor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("GroupId")
                        .HasColumnName("GroupId")
                        .HasColumnType("int(11)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsLifeSaving")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MainUnit")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SaremaCategory")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SubUnit")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("DrugId");

                    b.HasIndex("GroupId");

                    b.ToTable("drugs");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransferdetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DetailID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("TransferId")
                        .HasColumnName("TransferID")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("TransferId");

                    b.ToTable("drugtransferdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransfers", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TransferID")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<int>("FromBranchId")
                        .HasColumnName("FromBranchID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("JournalId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("ReceiptJournalId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ToBranchId")
                        .HasColumnName("ToBranchID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransferId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ToBranchId");

                    b.ToTable("drugtransfers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Employees", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Forecasts", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ForecastID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("date");

                    b.Property<int>("PredictedDemand")
                        .HasColumnType("int(11)");

                    b.HasKey("ForecastId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.ToTable("forecasts");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Fundtransfers", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TransferID")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<int>("FromAccountId")
                        .HasColumnName("FromAccountID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("JournalId")
                        .HasColumnName("JournalId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ToAccountId")
                        .HasColumnName("ToAccountID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransferId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("JournalId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("fundtransfers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.ItemGroups", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GroupId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("GroupCode")
                        .HasColumnName("GroupCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnName("GroupName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GroupId");

                    b.ToTable("itemgroups");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journaldetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DetailID")
                        .HasColumnType("int(11)");

                    b.Property<int>("AccountId")
                        .HasColumnName("AccountID")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("JournalId")
                        .HasColumnName("JournalID")
                        .HasColumnType("int(11)");

                    b.HasKey("DetailId");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalId");

                    b.ToTable("journaldetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journalentries", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("JournalID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("ReferenceType")
                        .HasColumnType("varchar(50)");

                    b.HasKey("JournalId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("journalentries");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PlanId")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("EstimatedTotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("PlanId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("purchaseplans");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlanDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DetailId")
                        .HasColumnType("int(11)");

                    b.Property<string>("ABCCategory")
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("ForecastAccuracy")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ForecastedDemand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsLifeSaving")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnName("PlanId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ProposedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCostEstimate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PlanId");

                    b.ToTable("purchaseplandetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchasedetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DetailID")
                        .HasColumnType("int(11)");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("BonusQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PurchaseId")
                        .HasColumnName("PurchaseID")
                        .HasColumnType("int(11)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchasedetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchases", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PurchaseID")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InvoiceImagePath")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ParentPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("PurchaseId");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SalePayments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PaymentId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("AccountId")
                        .HasColumnName("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SaleId")
                        .HasColumnName("SaleId")
                        .HasColumnType("int(11)");

                    b.HasKey("PaymentId");

                    b.HasIndex("AccountId");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_payments");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Saledetails", b =>
                {
                    b.Property<int>("SaleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SaleDetailID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int>("SaleId")
                        .HasColumnName("SaleID")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("SaleDetailId");

                    b.HasIndex("DrugId");

                    b.HasIndex("SaleId");

                    b.ToTable("saledetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Sales", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SaleID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("CustomerId")
                        .HasColumnName("CustomerID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsReturn")
                        .IsConcurrencyToken()
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ParentSaleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("SaleId")
                        .HasName("PRIMARY");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Screenpermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PermissionID")
                        .HasColumnType("int(11)");

                    b.Property<bool>("CanAdd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanPrint")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID")
                        .HasColumnType("int(11)");

                    b.Property<int>("ScreenId")
                        .HasColumnName("ScreenID")
                        .HasColumnType("int(11)");

                    b.HasKey("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("screenpermissions");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Seasonaldata", b =>
                {
                    b.Property<int>("SeasonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SeasonalID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SeasonalFactor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Year")
                        .HasColumnType("int(11)");

                    b.HasKey("SeasonalId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.ToTable("seasonaldata");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Shelves", b =>
                {
                    b.Property<int>("ShelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ShelfId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("GroupId")
                        .HasColumnName("GroupId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnName("Notes")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ShelfName")
                        .IsRequired()
                        .HasColumnName("ShelfName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("WarehouseId")
                        .HasColumnName("WarehouseId")
                        .HasColumnType("int(11)");

                    b.HasKey("ShelfId");

                    b.HasIndex("GroupId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("shelves");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockauditdetails", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<int>("Difference")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int(11)");

                    b.Property<int>("PhysicalQty")
                        .HasColumnType("int");

                    b.Property<int>("SystemQty")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DetailId");

                    b.HasIndex("AuditId");

                    b.HasIndex("DrugId");

                    b.ToTable("stockauditdetails");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockaudits", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("AuditId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("stockaudits");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockmovements", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MovementID")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("DrugId")
                        .HasColumnName("DrugID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnName("ReferenceID")
                        .HasColumnType("int(11)");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("MovementId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DrugId");

                    b.HasIndex("UserId");

                    b.ToTable("stockmovements");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Suppliers", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.HasKey("SupplierId");

                    b.HasIndex("AccountId");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SystemLogs", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("ScreenName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("systemlogs");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Systemscreens", b =>
                {
                    b.Property<int>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ScreenID")
                        .HasColumnType("int(11)");

                    b.Property<string>("ScreenArabicName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ScreenCategory")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScreenId");

                    b.ToTable("systemscreens");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Userroles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleID")
                        .HasColumnType("int(11)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleArabicName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("userroles");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("DefaultBranchId")
                        .HasColumnName("DefaultBranchID")
                        .HasColumnType("int(11)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID")
                        .HasColumnType("int(11)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("RoleId")
                        .HasColumnName("RoleID")
                        .HasColumnType("int(11)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("UserId");

                    b.HasIndex("DefaultBranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Vouchers", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VoucherID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchID")
                        .HasColumnType("int(11)");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("CreatedBy")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FromAccountId")
                        .HasColumnName("FromAccountID")
                        .HasColumnType("int(11)");

                    b.Property<int>("ToAccountId")
                        .HasColumnName("ToAccountID")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnName("VoucherDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasColumnName("VoucherType")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("VoucherId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("vouchers");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Warehouses", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WarehouseId")
                        .HasColumnType("int(11)");

                    b.Property<int>("BranchId")
                        .HasColumnName("BranchId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnName("Location")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasColumnName("WarehouseName")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("WarehouseId");

                    b.HasIndex("BranchId");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountMapping", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.AccountingTemplateLine", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.AccountingTemplate", "Template")
                        .WithMany("Lines")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Accounts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ParentAccount")
                        .WithMany("SubAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BarcodeGenerator", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("BarcodeQueue")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("BarcodeGenerator")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.BranchAccounts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("BranchAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("BranchAccounts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branches", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultCOGSAccount")
                        .WithMany("CogsBranches")
                        .HasForeignKey("DefaultCOGSAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultCashAccount")
                        .WithMany("CashBranches")
                        .HasForeignKey("DefaultCashAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Currencies", "DefaultCurrency")
                        .WithMany("Branches")
                        .HasForeignKey("DefaultCurrencyId");

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultInventoryAccount")
                        .WithMany("InventoryBranches")
                        .HasForeignKey("DefaultInventoryAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "DefaultSalesAccount")
                        .WithMany("SalesBranches")
                        .HasForeignKey("DefaultSalesAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Branchinventory", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Branchinventory")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Branchinventory")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Customers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Customers")
                        .HasForeignKey("AccountId")
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.DrugBatches", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("DrugBatches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugs", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.ItemGroups", "ItemGroup")
                        .WithMany("Drugs")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransferdetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Drugtransferdetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugtransfers", "Transfer")
                        .WithMany("Drugtransferdetails")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Drugtransfers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Users", "CreatedByNavigation")
                        .WithMany("Drugtransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Branches", "FromBranch")
                        .WithMany("DrugtransfersFromBranch")
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "ReceivedByNavigation")
                        .WithMany()
                        .HasForeignKey("ReceivedBy");

                    b.HasOne("PharmaSmartWeb.Models.Branches", "ToBranch")
                        .WithMany("DrugtransfersToBranch")
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Employees", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Forecasts", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Forecasts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Forecasts")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Fundtransfers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Fundtransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "FromAccount")
                        .WithMany("FundtransfersFromAccount")
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Journalentries", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ToAccount")
                        .WithMany("FundtransfersToAccount")
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journaldetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Journaldetails")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Journalentries", "Journal")
                        .WithMany("Journaldetails")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Journalentries", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Journalentries")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "CreatedByNavigation")
                        .WithMany("Journalentries")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlan", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.PurchasePlanDetail", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.PurchasePlan", "PurchasePlan")
                        .WithMany("PlanDetails")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchasedetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Purchasedetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Purchases", "Purchase")
                        .WithMany("Purchasedetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Purchases", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Purchases")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Suppliers", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SalePayments", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("SalePayments")
                        .HasForeignKey("AccountId");

                    b.HasOne("PharmaSmartWeb.Models.Sales", "Sale")
                        .WithMany("SalePayments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Saledetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Saledetails")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Sales", "Sale")
                        .WithMany("Saledetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Sales", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Sales")
                        .HasForeignKey("BranchId")
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Customers", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Screenpermissions", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Userroles", "Role")
                        .WithMany("Screenpermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Systemscreens", "Screen")
                        .WithMany("Screenpermissions")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Seasonaldata", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Seasonaldata")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Seasonaldata")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Shelves", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.ItemGroups", "ItemGroup")
                        .WithMany("Shelves")
                        .HasForeignKey("GroupId");

                    b.HasOne("PharmaSmartWeb.Models.Warehouses", "Warehouse")
                        .WithMany("Shelves")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockauditdetails", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Stockaudits", "Audit")
                        .WithMany("Stockauditdetails")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockaudits", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Stockaudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Stockmovements", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Stockmovements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Drugs", "Drug")
                        .WithMany("Stockmovements")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Stockmovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Suppliers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Accounts", "Account")
                        .WithMany("Suppliers")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.SystemLogs", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany("Systemlogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Users", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "DefaultBranch")
                        .WithMany("Users")
                        .HasForeignKey("DefaultBranchId");

                    b.HasOne("PharmaSmartWeb.Models.Employees", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PharmaSmartWeb.Models.Userroles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Vouchers", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "FromAccount")
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaSmartWeb.Models.Accounts", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaSmartWeb.Models.Warehouses", b =>
                {
                    b.HasOne("PharmaSmartWeb.Models.Branches", "Branch")
                        .WithMany("Warehouses")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
